# https://taskfile.dev
version: "3"

dotenv: [".env", ".env.local"]

vars:
  ENGINE_DIR: ./crates/engine
  PLAYER_DIR: ./crates/player
  PROTOCOL_DIR: ./crates/protocol

env:
  RUST_LOG: info,wrldbldr_engine=debug,wrldbldr_player=debug
  NEO4J_PASSWORD: wrldbldr123

tasks:
  # ===========================================================================
  # Development - Run Services
  # ===========================================================================

  dev:
    desc: Run both backend and frontend using Overmind
    cmds:
      - overmind start -f Procfile.dev
    interactive: true

  backend:
    desc: Run the Engine backend server
    dir: "{{.ENGINE_DIR}}"
    cmds:
      - cargo run -p wrldbldr-engine --bin wrldbldr-engine
    env:
      RUST_LOG: info,wrldbldr_engine=debug
      NEO4J_PASSWORD: wrldbldr123

  web:dev:
    desc: Run the Player frontend in web/WASM mode with hot reload
    cmds:
      - task: css:build
      - dx serve --web --open
    dir: "{{.PLAYER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug
      NEO4J_PASSWORD: wrldbldr123

  web:dev:headless:
    desc: Run the Player frontend web dev (no auto-open)
    cmds:
      - task: css:build
      - dx serve --web --open=false
    dir: "{{.PLAYER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug
      NEO4J_PASSWORD: wrldbldr123

  desktop:dev:
    desc: Run the Player frontend in desktop mode
    cmds:
      - task: css:build
      - cargo run -p wrldbldr-player --bin wrldbldr-player
    dir: "{{.PLAYER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug

  # ===========================================================================
  # Build Tasks
  # ===========================================================================

  build:
    desc: Build all crates (debug mode)
    deps:
      - arch-check
    cmds:
      - cargo build --workspace

  build:release:
    desc: Build all crates (release mode)
    deps:
      - arch-check
    cmds:
      - cargo build --workspace --release

  build:engine:
    desc: Build the Engine backend
    cmds:
      - cargo build -p wrldbldr-engine

  build:player:
    desc: Build the Player frontend (native)
    cmds:
      - task: css:build
      - cargo build -p wrldbldr-player --bin wrldbldr-player

  build:web:
    desc: Build the Player frontend for web/WASM
    dir: "{{.PLAYER_DIR}}"
    cmds:
      - task: css:build
      - dx build --web --release

  # ===========================================================================
  # Check & Test Tasks
  # ===========================================================================

  check:
    desc: Check all crates for errors
    cmds:
      - cargo check --workspace

  check:engine:
    desc: Check Engine crate
    cmds:
      - cargo check -p wrldbldr-engine

  check:player:
    desc: Check Player crate
    cmds:
      - cargo check -p wrldbldr-player

  check:protocol:
    desc: Check Protocol crate
    cmds:
      - cargo check -p wrldbldr-shared

  test:
    desc: Run all tests
    cmds:
      - cargo test --workspace

  test:engine:
    desc: Run Engine tests
    cmds:
      - cargo test -p wrldbldr-engine

  test:player:
    desc: Run Player tests
    cmds:
      - cargo test -p wrldbldr-player

  test:protocol:
    desc: Run Protocol tests
    cmds:
      - cargo test -p wrldbldr-shared

  # ===========================================================================
  # E2E Tests (require Docker for testcontainers)
  # ===========================================================================

  e2e:
    desc: Run E2E tests with VCR playback (fast, no Ollama needed)
    cmds:
      - cargo test -p wrldbldr-engine --lib e2e_tests -- --ignored --test-threads=1 --nocapture
    env:
      RUST_LOG: info,wrldbldr_engine=debug

  e2e:record:
    desc: Run E2E tests in record mode (requires Ollama running)
    cmds:
      - cargo test -p wrldbldr-engine --lib e2e_tests -- --ignored --test-threads=1 --nocapture
    env:
      E2E_LLM_MODE: record
      RUST_LOG: info,wrldbldr_engine=debug

  e2e:live:
    desc: Run E2E tests in live mode (always calls Ollama, no recording)
    cmds:
      - cargo test -p wrldbldr-engine --lib e2e_tests -- --ignored --test-threads=1 --nocapture
    env:
      E2E_LLM_MODE: live
      RUST_LOG: info,wrldbldr_engine=debug

  e2e:single:
    desc: "Run a single E2E test (usage: task e2e:single -- test_name)"
    cmds:
      - cargo test -p wrldbldr-engine --lib "e2e_tests::{{.CLI_ARGS}}" -- --ignored --nocapture
    env:
      RUST_LOG: info,wrldbldr_engine=debug

  e2e:logs:
    desc: Show E2E event logs directory
    cmds:
      - ls -la crates/engine/src/e2e_tests/logs/

  e2e:logs:view:
    desc: "View E2E log summary (usage: task e2e:logs:view -- test_name)"
    cmds:
      - cat crates/engine/src/e2e_tests/logs/{{.CLI_ARGS}}.json | jq '.summary'

  e2e:logs:prompts:
    desc: "View LLM prompts from E2E log (usage: task e2e:logs:prompts -- test_name)"
    cmds:
      - cat crates/engine/src/e2e_tests/logs/{{.CLI_ARGS}}.json | jq '.events[] | select(.event.type == "LlmPromptSent")'

  e2e:logs:conversations:
    desc: "View conversation turns from E2E log (usage: task e2e:logs:conversations -- test_name)"
    cmds:
      - cat crates/engine/src/e2e_tests/logs/{{.CLI_ARGS}}.json | jq '.events[] | select(.event.type == "ConversationTurn" or .event.type == "ConversationStarted")'

  # ===========================================================================
  # Architecture Enforcement
  # ===========================================================================

  arch-check:
    desc: Validate hexagonal architecture dependencies
    cmds:
      - cargo xtask arch-check

  # ===========================================================================
  # Code Quality
  # ===========================================================================

  fmt:
    desc: Format all code
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --all -- --check

  clippy:
    desc: Run Clippy linter
    cmds:
      - cargo clippy --workspace -- -D warnings

  lint:
    desc: Run all linting (fmt check + clippy)
    cmds:
      - task: fmt:check
      - task: clippy

  # ===========================================================================
  # Statistics
  # ===========================================================================

  stats:
    desc: "Count lines of code per crate and show total (requires tokei: cargo install tokei)"
    cmds:
      - |
        if command -v tokei > /dev/null 2>&1; then
          echo "=== Lines of Code Statistics ==="
          echo ""
          total=0
          for crate in crates/*/; do
            if [ -d "$crate/src" ] || [ -f "$crate/Cargo.toml" ]; then
              crate_name=$(basename "$crate")
              rust_lines=$(tokei "$crate" --output json 2>/dev/null | jq -r '.Rust.code // 0' 2>/dev/null || echo "0")
              if [ "$rust_lines" != "0" ] && [ -n "$rust_lines" ]; then
                printf "%-25s %8s lines\n" "$crate_name" "$rust_lines"
                total=$((total + rust_lines))
              fi
            fi
          done
          echo "─────────────────────────────────────────"
          printf "%-25s %8s lines\n" "TOTAL" "$total"
        else
          echo "Error: tokei is not installed."
          echo "Install it with: cargo install tokei"
          echo ""
          echo "Alternatively, using basic line count:"
          echo ""
          total=0
          for crate in crates/*/; do
            if [ -d "$crate/src" ]; then
              crate_name=$(basename "$crate")
              count=$(find "$crate/src" -name "*.rs" -type f 2>/dev/null | xargs cat 2>/dev/null | wc -l || echo "0")
              if [ "$count" != "0" ] && [ -n "$count" ]; then
                printf "%-25s %8s lines\n" "$crate_name" "$count"
                total=$((total + count))
              fi
            fi
          done
          echo "─────────────────────────────────────────"
          printf "%-25s %8s lines\n" "TOTAL" "$total"
        fi

  # ===========================================================================
  # Frontend Tooling
  # ===========================================================================

  css:build:
    desc: Build Tailwind CSS
    dir: "{{.PLAYER_DIR}}"
    cmds:
      - npm run build:css

  css:watch:
    desc: Watch and rebuild Tailwind CSS
    dir: "{{.PLAYER_DIR}}"
    cmds:
      - npm run watch:css

  npm:install:
    desc: Install npm dependencies for Player UI
    dir: "{{.PLAYER_DIR}}"
    cmds:
      - npm install

  # ===========================================================================
  # Database & Infrastructure
  # ===========================================================================

  docker:up:
    desc: Start Docker services (Neo4j, etc.)
    dir: ./docker
    cmds:
      - docker-compose up -d

  docker:deps:up:
    desc: Start Docker dependencies (Neo4j)
    dir: ./docker
    cmds:
      - docker-compose up -d neo4j

  docker:deps:down:
    desc: Stop Docker dependencies (Neo4j)
    dir: ./docker
    cmds:
      - docker-compose stop neo4j
 
  docker:down:
    desc: Stop Docker
    dir: ./docker
    cmds:
      - docker-compose down

  docker:down:
    desc: Stop Docker services
    dir: ./docker
    cmds:
      - docker-compose down

  docker:logs:
    desc: Show Docker service logs
    dir: ./docker
    cmds:
      - docker-compose logs -f

  docker:neo4j:reset:
    desc: Remove Neo4j data and logs volumes (requires neo4j to be stopped)
    cmds:
      - docker volume rm docker_neo4j_data docker_neo4j_logs

  # ===========================================================================
  # Clean Tasks
  # ===========================================================================

  clean:
    desc: Clean all build artifacts
    cmds:
      - cargo clean

  clean:player:
    desc: Clean Player build artifacts (including dx dist)
    dir: "{{.PLAYER_DIR}}"
    cmds:
      - cargo clean
      - rm -rf dist/

  # ===========================================================================
  # Setup Tasks
  # ===========================================================================

  setup:
    desc: Initial project setup
    cmds:
      - task: npm:install
      - echo "Setup complete! Run 'task dev' to start development."

  setup:wasm:
    desc: Install WASM target for Rust
    cmds:
      - rustup target add wasm32-unknown-unknown

  # ===========================================================================
  # Documentation
  # ===========================================================================

  docs:
    desc: Generate and open documentation
    cmds:
      - cargo doc --workspace --no-deps --open

  docs:build:
    desc: Generate documentation without opening
    cmds:
      - cargo doc --workspace --no-deps
