# https://taskfile.dev
version: '3'

vars:
  ENGINE_DIR: ./crates/engine-runner
  PLAYER_RUNNER_DIR: ./crates/player-runner
  PLAYER_UI_DIR: ./crates/player-ui
  PROTOCOL_DIR: ./crates/protocol

env:
  RUST_LOG: info,wrldbldr_engine=debug,wrldbldr_player=debug
  NEO4J_PASSWORD: wrldbldr123

tasks:
  # ===========================================================================
  # Development - Run Services
  # ===========================================================================

  dev:
    desc: Run both backend and frontend using Overmind
    cmds:
      - overmind start -f Procfile.dev
    interactive: true

  backend:
    desc: Run the Engine backend server
    dir: "{{.ENGINE_DIR}}"
    cmds:
      - cargo run --bin wrldbldr-engine
    env:
      RUST_LOG: info,wrldbldr_engine=debug
      NEO4J_PASSWORD: wrldbldr123

  web:dev:
    desc: Run the Player frontend in web/WASM mode with hot reload
    cmds:
      - task: css:build
      - dx serve --web --open
    dir: "{{.PLAYER_RUNNER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug
      NEO4J_PASSWORD: wrldbldr123

  web:dev:headless:
    desc: Run the Player frontend web dev (no auto-open)
    cmds:
      - task: css:build
      - dx serve --web --open=false
    dir: "{{.PLAYER_RUNNER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug
      NEO4J_PASSWORD: wrldbldr123

  desktop:dev:
    desc: Run the Player frontend in desktop mode
    cmds:
      - task: css:build
      - cargo run -p wrldbldr-player-runner --bin wrldbldr-player
    dir: "{{.PLAYER_RUNNER_DIR}}"
    env:
      RUST_LOG: info,wrldbldr_player=debug

  # ===========================================================================
  # Build Tasks
  # ===========================================================================

  build:
    desc: Build all crates (debug mode)
    cmds:
      - cargo build --workspace

  build:release:
    desc: Build all crates (release mode)
    cmds:
      - cargo build --workspace --release

  build:engine:
    desc: Build the Engine backend
    cmds:
      - cargo build -p wrldbldr-engine-runner

  build:player:
    desc: Build the Player frontend (native)
    cmds:
      - task: css:build
      - cargo build -p wrldbldr-player-runner --bin wrldbldr-player

  build:web:
    desc: Build the Player frontend for web/WASM
    dir: "{{.PLAYER_RUNNER_DIR}}"
    cmds:
      - task: css:build
      - dx build --web --release

  # ===========================================================================
  # Check & Test Tasks
  # ===========================================================================

  check:
    desc: Check all crates for errors
    cmds:
      - cargo check --workspace

  check:engine:
    desc: Check Engine crate
    cmds:
      - cargo check -p wrldbldr-engine-runner

  check:player:
    desc: Check Player runner crate
    cmds:
      - cargo check -p wrldbldr-player-runner

  check:protocol:
    desc: Check Protocol crate
    cmds:
      - cargo check -p wrldbldr-protocol

  test:
    desc: Run all tests
    cmds:
      - cargo test --workspace

  test:engine:
    desc: Run Engine tests
    cmds:
      - cargo test -p wrldbldr-engine-runner

  test:player:
    desc: Run Player runner tests
    cmds:
      - cargo test -p wrldbldr-player-runner

  test:protocol:
    desc: Run Protocol tests
    cmds:
      - cargo test -p wrldbldr-protocol

  # ===========================================================================
  # Code Quality
  # ===========================================================================

  fmt:
    desc: Format all code
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting
    cmds:
      - cargo fmt --all -- --check

  clippy:
    desc: Run Clippy linter
    cmds:
      - cargo clippy --workspace -- -D warnings

  lint:
    desc: Run all linting (fmt check + clippy)
    cmds:
      - task: fmt:check
      - task: clippy

  # ===========================================================================
  # Frontend Tooling
  # ===========================================================================

  css:build:
    desc: Build Tailwind CSS
    dir: "{{.PLAYER_UI_DIR}}"
    cmds:
      - npm run build:css

  css:watch:
    desc: Watch and rebuild Tailwind CSS
    dir: "{{.PLAYER_UI_DIR}}"
    cmds:
      - npm run watch:css

  npm:install:
    desc: Install npm dependencies for Player UI
    dir: "{{.PLAYER_UI_DIR}}"
    cmds:
      - npm install

  # ===========================================================================
  # Database & Infrastructure
  # ===========================================================================

  docker:up:
    desc: Start Docker services (Neo4j, etc.)
    dir: ./docker
    cmds:
      - docker-compose up -d

  docker:down:
    desc: Stop Docker services
    dir: ./docker
    cmds:
      - docker-compose down

  docker:logs:
    desc: Show Docker service logs
    dir: ./docker
    cmds:
      - docker-compose logs -f

  # ===========================================================================
  # Clean Tasks
  # ===========================================================================

  clean:
    desc: Clean all build artifacts
    cmds:
      - cargo clean

  clean:player:
    desc: Clean Player build artifacts (including dx dist)
    dir: "{{.PLAYER_RUNNER_DIR}}"
    cmds:
      - cargo clean
      - rm -rf dist/

  # ===========================================================================
  # Setup Tasks
  # ===========================================================================

  setup:
    desc: Initial project setup
    cmds:
      - task: npm:install
      - echo "Setup complete! Run 'task dev' to start development."

  setup:wasm:
    desc: Install WASM target for Rust
    cmds:
      - rustup target add wasm32-unknown-unknown

  # ===========================================================================
  # Documentation
  # ===========================================================================

  docs:
    desc: Generate and open documentation
    cmds:
      - cargo doc --workspace --no-deps --open

  docs:build:
    desc: Generate documentation without opening
    cmds:
      - cargo doc --workspace --no-deps
