extern crate self as wrldbldr_domain;

pub mod aggregates;
pub mod entities;
pub mod error;
pub mod events;
pub mod game_time;
pub mod ids;
pub mod value_objects;

// Re-export all entities (explicit list in entities/mod.rs)
pub use entities::{
    default_skills_for_variant, AcquisitionMethod, Act, ActantialRole, ActantialView, AssetType,
    BatchStatus, ChainStatus, ChainedEvent, Challenge, ChallengeEventOutcome,
    ChallengeLocationAvailability, ChallengeOutcomes, ChallengePrerequisite,
    ChallengeRegionAvailability, ChallengeType, ChallengeUnlock, Character, CharacterSheetData,
    CharacterSheetTemplate, CharacterWant, CombatEventType, CombatOutcome, Difficulty,
    DifficultyDescriptor, DmMarkerType, EntityType, EventChain, EventChainMembership, EventEffect,
    EventOutcome, FeaturedNpc, FieldType, FieldValue, FlagScope, FrequencyLevel, GalleryAsset,
    GameFlag, GenerationBatch, GenerationMetadata, GenerationRequest, Goal, GridMap, InfoType,
    InputDefault, InputType, InteractionCondition, InteractionRequirement, InteractionTarget,
    InteractionTargetType, InteractionTemplate, InteractionType, InventoryItem, InvolvedCharacter,
    Item, ItemListType, ItemSource, Location, LocationConnection, LocationType, MapBounds,
    MarkerImportance, MonomythStage, NarrativeEvent, NarrativeTrigger, NarrativeTriggerType,
    NpcObservation, ObservationSummary, ObservationType, Outcome, OutcomeCondition, OutcomeTrigger,
    OutcomeType, PlayerCharacter, PromptMapping, PromptMappingType, Region, RegionConnection,
    RegionExit, Scene, SceneCharacter, SceneCharacterRole, SceneCondition, SectionLayout,
    SelectOption, SheetField, SheetSection, SheetTemplateId, Skill, SkillCategory, StagedNpc,
    Staging, StagingSource, StatBlock, StoryEvent, StoryEventInfoImportance, StoryEventType,
    TimeContext, TriggerCondition, TriggerContext, TriggerEvaluation, TriggerLogic, TriggerType,
    Want, WantTargetType, WantVisibility, WorkflowAnalysis, WorkflowConfiguration, WorkflowInput,
    WorkflowSlot, World,
};

pub use error::DomainError;
pub use events::DomainEvent;

// Re-export game time types
pub use game_time::{GameTime, TimeOfDay};

// Re-export ID types
pub use ids::{
    ActId, ActionId, AssetId, BatchId, ChallengeId, CharacterId, EventChainId, EventId, GoalId,
    GridMapId, InteractionId, ItemId, LocationId, NarrativeEventId, ParticipantId,
    PlayerCharacterId, QueueItemId, RegionId, RelationshipId, SceneId, SkillId, StagingId,
    StoryEventId, UserId, WantId, WorkflowConfigId, WorkflowId, WorldId,
};

// Re-export value objects (explicit list in value_objects/mod.rs)
pub use value_objects::{
    count_tokens,
    exceeds_token_budget,
    get_prompt_default,
    key_to_env_var,
    prompt_defaults,
    prompt_keys,
    prompt_template_keys,
    prompt_template_metadata,
    settings_metadata,
    ActantialActor,
    ActantialActorEntry,
    ActantialContext,
    ActantialLLMContext,
    ActantialTarget,
    ActiveChallengeContext,
    ActiveEventContext,
    ActiveNarrativeEventContext,
    ActorType,
    AppSettings,
    // Queue data value objects
    ApprovalDecisionType,
    ApprovalRequestData,
    ApprovalType,
    ApprovalUrgency,
    ArchetypeChange,
    AssetGenerationData,
    CampbellArchetype,
    ChallengeOutcomeData,
    ChallengeSignificance,
    ChallengeSuggestion,
    ChallengeSuggestionOutcomes,
    ChangeAmount,
    CharacterContext,
    ComfyUIConfig,
    ContextBudgetConfig,
    ContextCategory,
    ConversationEntry,
    ConversationTurn,
    DiceRollInput,
    DiceSystem,
    DirectorialNotes,
    DispositionLevel,
    DmActionData,
    DmActionType,
    DmApprovalDecision,
    DomainNpcMotivation,
    FamilyRelation,
    GamePromptRequest,
    GameTool,
    InfoImportance,
    InteractionOutcome,
    LlmRequestData,
    LlmRequestType,
    MotivationEntry,
    MotivationsContext,
    NarrativeEventSuggestion,
    NpcDialogueContext,
    NpcDispositionState,
    PacingGuidance,
    PendingApprovalItem,
    PlayerActionContext,
    PlayerActionData,
    PromptTemplateCategory,
    PromptTemplateMetadata,
    ProposedTool,
    RegionFrequency,
    RegionItemContext,
    RegionRelationship,
    RegionRelationshipType,
    RegionShift,
    Relationship,
    RelationshipChange,
    RelationshipEvent,
    RelationshipLevel,
    RelationshipType,
    RollResult,
    RuleBasedSuggestion,
    RuleSystemConfig,
    RuleSystemType,
    RuleSystemVariant,
    SceneContext,
    SecretMotivationContext,
    SecretMotivationEntry,
    SettingsFieldMetadata,
    SocialRelationEntry,
    SocialStanceContext,
    SocialViewSummary,
    Speaker,
    StagingContext,
    StatDefinition,
    SuccessComparison,
    SuggestionContext,
    TokenCountMethod,
    TokenCounter,
    ToneGuidance,
    WantContext,
    WantTarget,
};
