//! Skill entity - Character skills tied to rule systems
//!
//! Skills are defined per-world and can be either:
//! - Default skills from a rule system preset
//! - Custom skills created by the DM

use serde::{Deserialize, Serialize};

use crate::value_objects::{RuleSystemVariant, Stat};
use wrldbldr_domain::{DomainError, SkillId, WorldId};

/// A skill that characters can use for challenges.
///
/// ADR-008 Tier 4: Simple data struct with public fields because:
/// - No invariants to protect
/// - No validation required between fields
/// - Just groups related data for persistence and transfer
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Skill {
    pub id: SkillId,
    pub world_id: WorldId,
    pub name: String,
    pub description: String,
    /// Category for UI grouping (e.g., "Physical", "Mental", "Social")
    pub category: SkillCategory,
    /// The base attribute this skill derives from (e.g., Dex, Int)
    pub base_attribute: Option<Stat>,
    /// Whether this is a custom skill (not from preset)
    pub is_custom: bool,
    /// Whether to hide this skill from players
    pub is_hidden: bool,
    /// Display order within category
    pub order: u32,
}

impl Skill {
    pub fn new(world_id: WorldId, name: impl Into<String>, category: SkillCategory) -> Self {
        Self {
            id: SkillId::new(),
            world_id,
            name: name.into(),
            description: String::new(),
            category,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 0,
        }
    }

    pub fn custom(world_id: WorldId, name: impl Into<String>, category: SkillCategory) -> Self {
        let mut skill = Self::new(world_id, name, category);
        skill.is_custom = true;
        skill
    }

    /// Reconstruct a Skill from storage
    #[allow(clippy::too_many_arguments)]
    pub fn from_storage(
        id: SkillId,
        world_id: WorldId,
        name: String,
        description: String,
        category: SkillCategory,
        base_attribute: Option<Stat>,
        is_custom: bool,
        is_hidden: bool,
        order: u32,
    ) -> Self {
        Self {
            id,
            world_id,
            name,
            description,
            category,
            base_attribute,
            is_custom,
            is_hidden,
            order,
        }
    }
}

/// Skill categories for UI organization
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub enum SkillCategory {
    // D20 style categories
    Physical,
    Mental,
    Social,

    // D100/CoC style categories
    Interpersonal,
    Investigation,
    Academic,
    Practical,
    Combat,

    // Narrative style
    Approach,
    Aspect,

    // General
    Other,
    Custom,

    /// Unknown category for forward compatibility
    #[serde(other)]
    Unknown,
}

impl SkillCategory {
    pub fn display_name(&self) -> &'static str {
        match self {
            Self::Physical => "Physical",
            Self::Mental => "Mental",
            Self::Social => "Social",
            Self::Interpersonal => "Interpersonal",
            Self::Investigation => "Investigation",
            Self::Academic => "Academic",
            Self::Practical => "Practical",
            Self::Combat => "Combat",
            Self::Approach => "Approach",
            Self::Aspect => "Aspect",
            Self::Other => "Other",
            Self::Custom => "Custom",
            Self::Unknown => "Unknown",
        }
    }
}

impl std::fmt::Display for SkillCategory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.display_name())
    }
}

impl std::str::FromStr for SkillCategory {
    type Err = DomainError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "physical" => Ok(Self::Physical),
            "mental" => Ok(Self::Mental),
            "social" => Ok(Self::Social),
            "interpersonal" => Ok(Self::Interpersonal),
            "investigation" => Ok(Self::Investigation),
            "academic" => Ok(Self::Academic),
            "practical" => Ok(Self::Practical),
            "combat" => Ok(Self::Combat),
            "approach" => Ok(Self::Approach),
            "aspect" => Ok(Self::Aspect),
            "other" => Ok(Self::Other),
            "custom" => Ok(Self::Custom),
            _ => Err(DomainError::parse(format!("Unknown skill category: {}", s))),
        }
    }
}

/// Default skills for each rule system variant
pub fn default_skills_for_variant(world_id: WorldId, variant: &RuleSystemVariant) -> Vec<Skill> {
    match variant {
        RuleSystemVariant::Dnd5e => dnd5e_skills(world_id),
        RuleSystemVariant::Pathfinder2e => pathfinder2e_skills(world_id),
        RuleSystemVariant::GenericD20 => generic_d20_skills(world_id),
        RuleSystemVariant::CallOfCthulhu7e => coc7e_skills(world_id),
        RuleSystemVariant::RuneQuest => runequest_skills(world_id),
        RuleSystemVariant::GenericD100 => generic_d100_skills(world_id),
        RuleSystemVariant::KidsOnBikes => kids_on_bikes_skills(world_id),
        RuleSystemVariant::FateCore => fate_core_skills(world_id),
        RuleSystemVariant::PoweredByApocalypse => pbta_skills(world_id),
        RuleSystemVariant::BladesInTheDark => blades_skills(world_id),
        RuleSystemVariant::Custom(_) | RuleSystemVariant::Unknown => vec![],
    }
}

// D&D 5e Skills
fn dnd5e_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        // STR skills
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: "Climbing, swimming, jumping, and physical exertion".to_string(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Str),
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        // DEX skills
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Acrobatics".to_string(),
            description: "Balance, tumbling, and aerial maneuvers".to_string(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Sleight of Hand".to_string(),
            description: "Pickpocketing, concealing objects, manual trickery".to_string(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: "Moving silently and hiding".to_string(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        // INT skills
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Arcana".to_string(),
            description: "Knowledge of spells, magic items, and magical traditions".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "History".to_string(),
            description: "Knowledge of historical events, people, and legends".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Investigation".to_string(),
            description: "Deduction, searching for clues, making inferences".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Nature".to_string(),
            description: "Knowledge of terrain, plants, animals, and weather".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Religion".to_string(),
            description: "Knowledge of deities, rites, and religious traditions".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        // WIS skills
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Animal Handling".to_string(),
            description: "Calming, training, and directing animals".to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Insight".to_string(),
            description: "Reading body language, detecting lies, understanding motivations"
                .to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Medicine".to_string(),
            description: "Diagnosing illnesses, stabilizing the dying, treating wounds".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Perception".to_string(),
            description: "Noticing threats, spotting hidden objects, general awareness".to_string(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 13,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Survival".to_string(),
            description: "Tracking, foraging, navigating wilderness".to_string(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 14,
        },
        // CHA skills
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Deception".to_string(),
            description: "Lying, misleading, disguising intentions".to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 15,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Intimidation".to_string(),
            description: "Threatening, coercing, inspiring fear".to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 16,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Performance".to_string(),
            description: "Acting, music, storytelling, entertainment".to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 17,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Persuasion".to_string(),
            description: "Convincing, negotiating, influencing through tact".to_string(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 18,
        },
    ]
}

// Pathfinder 2e Skills
fn pathfinder2e_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Acrobatics".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Arcana".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Str),
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Crafting".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Deception".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Diplomacy".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Intimidation".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Medicine".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Nature".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Occultism".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Performance".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Religion".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Society".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 13,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 14,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Survival".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 15,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Thievery".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 16,
        },
    ]
}

// Generic D20 (simplified)
fn generic_d20_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Str),
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Agility".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Dex),
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Endurance".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: Some(Stat::Con),
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Knowledge".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Int),
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Awareness".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: Some(Stat::Wis),
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Influence".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: Some(Stat::Cha),
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
    ]
}

// Call of Cthulhu 7e Skills
fn coc7e_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        // Interpersonal
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Charm".to_string(),
            description: "Physical attraction, seduction, flattery".to_string(),
            category: SkillCategory::Interpersonal,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Fast Talk".to_string(),
            description: "Con, deceive, lie, misdirect".to_string(),
            category: SkillCategory::Interpersonal,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Intimidate".to_string(),
            description: "Threats, physical coercion".to_string(),
            category: SkillCategory::Interpersonal,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Persuade".to_string(),
            description: "Reasoned argument, debate".to_string(),
            category: SkillCategory::Interpersonal,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Psychology".to_string(),
            description: "Understand motives, see through lies".to_string(),
            category: SkillCategory::Interpersonal,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        // Investigation
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Library Use".to_string(),
            description: "Navigate libraries, find information in documents".to_string(),
            category: SkillCategory::Investigation,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Spot Hidden".to_string(),
            description: "Spot concealed objects, notice things".to_string(),
            category: SkillCategory::Investigation,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Listen".to_string(),
            description: "Hear sounds, eavesdrop".to_string(),
            category: SkillCategory::Investigation,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Track".to_string(),
            description: "Follow tracks, signs of passage".to_string(),
            category: SkillCategory::Investigation,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        // Academic
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Accounting".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Anthropology".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Archaeology".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "History".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 13,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Law".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 14,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Medicine".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 15,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Natural World".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 16,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Occult".to_string(),
            description: "Knowledge of the Mythos and supernatural".to_string(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 17,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Science".to_string(),
            description: String::new(),
            category: SkillCategory::Academic,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 18,
        },
        // Practical
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Art/Craft".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 19,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Disguise".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 20,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Drive Auto".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 21,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Electrical Repair".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 22,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "First Aid".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 23,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Locksmith".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 24,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Mechanical Repair".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 25,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Navigate".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 26,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Sleight of Hand".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 27,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 28,
        },
        // Combat
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Dodge".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 29,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Fighting (Brawl)".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 30,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Firearms (Handgun)".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 31,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Firearms (Rifle/Shotgun)".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 32,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Throw".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 33,
        },
    ]
}

// RuneQuest (simplified)
fn runequest_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Brawn".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Endurance".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Evade".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Perception".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Willpower".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Deceit".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Influence".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Insight".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Locale".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Customs".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "First Aid".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 13,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Craft".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 14,
        },
    ]
}

// Generic D100
fn generic_d100_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Perception".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: String::new(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Investigation".to_string(),
            description: String::new(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Persuasion".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Deception".to_string(),
            description: String::new(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Combat".to_string(),
            description: String::new(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "First Aid".to_string(),
            description: String::new(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
    ]
}

// Kids on Bikes (stats as "skills")
fn kids_on_bikes_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Brains".to_string(),
            description: "Book smarts, problem solving, trivia".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Brawn".to_string(),
            description: "Physical strength, endurance, toughness".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Fight".to_string(),
            description: "Combat ability, self-defense".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Flight".to_string(),
            description: "Running away, escaping, hiding".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Charm".to_string(),
            description: "Social graces, persuasion, likability".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Grit".to_string(),
            description: "Willpower, courage, determination".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
    ]
}

// FATE Core Skills
fn fate_core_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Athletics".to_string(),
            description: "Running, jumping, climbing, general physical activity".to_string(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Burglary".to_string(),
            description: "Bypassing security, lockpicking, sleight of hand".to_string(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Contacts".to_string(),
            description: "Knowing people, gathering information through networks".to_string(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Crafts".to_string(),
            description: "Making and breaking things".to_string(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Deceive".to_string(),
            description: "Lying, misdirection, creating false impressions".to_string(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Drive".to_string(),
            description: "Operating vehicles".to_string(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Empathy".to_string(),
            description: "Reading people's emotions and intentions".to_string(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Fight".to_string(),
            description: "Close quarters combat".to_string(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Investigate".to_string(),
            description: "Finding clues, solving mysteries".to_string(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Lore".to_string(),
            description: "Specialized knowledge".to_string(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Notice".to_string(),
            description: "Spotting things, general awareness".to_string(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Physique".to_string(),
            description: "Raw strength, endurance".to_string(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Provoke".to_string(),
            description: "Intimidation, getting emotional reactions".to_string(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 13,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Rapport".to_string(),
            description: "Building trust, making friends".to_string(),
            category: SkillCategory::Social,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 14,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Resources".to_string(),
            description: "Wealth and material assets".to_string(),
            category: SkillCategory::Practical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 15,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Shoot".to_string(),
            description: "Ranged attacks".to_string(),
            category: SkillCategory::Combat,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 16,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Stealth".to_string(),
            description: "Staying unseen, tailing people".to_string(),
            category: SkillCategory::Physical,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 17,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Will".to_string(),
            description: "Mental fortitude, resisting influence".to_string(),
            category: SkillCategory::Mental,
            base_attribute: None,
            is_custom: false,
            is_hidden: false,
            order: 18,
        },
    ]
}

// Powered by the Apocalypse (basic moves as "skills")
fn pbta_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Act Under Pressure".to_string(),
            description: "Stay calm, keep your head when things go south".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Help/Interfere".to_string(),
            description: "Aid or hinder another character's action".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Go Aggro".to_string(),
            description: "Threaten violence to get what you want".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Seize by Force".to_string(),
            description: "Take something through direct violence".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Read a Sitch".to_string(),
            description: "Assess a dangerous situation".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Read a Person".to_string(),
            description: "Figure out what someone is really about".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Manipulate".to_string(),
            description: "Get someone to do what you want".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not the Stat enum
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Help/Interfere".to_string(),
            description: "Aid or hinder another character's action".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Go Aggro".to_string(),
            description: "Threaten violence to get what you want".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Seize by Force".to_string(),
            description: "Take something through direct violence".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Read a Sitch".to_string(),
            description: "Assess a dangerous situation".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Read a Person".to_string(),
            description: "Figure out what someone is really about".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Manipulate".to_string(),
            description: "Get someone to do what you want".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // PbtA uses custom stats, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 7,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Seduce".to_string(),
            description: "Use attraction to influence".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Open Your Brain".to_string(),
            description: "Tap into psychic maelstrom".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Read a Sitch".to_string(),
            description: "Assess a dangerous situation".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Skirmish".to_string(),
            description: "Close-quarters combat, melee fighting".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Wreck".to_string(),
            description: "Smash, breach, destroy with brute force".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
    ]
}

// Blades in the Dark (actions as "skills", grouped by attribute)
fn blades_skills(world_id: WorldId) -> Vec<Skill> {
    vec![
        // Insight actions
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Hunt".to_string(),
            description: "Track, ambush, or shoot from a distance".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 1,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Study".to_string(),
            description: "Scrutinize details, research, analyze".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 2,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Survey".to_string(),
            description: "Observe, spot trouble, gather information".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 3,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Tinker".to_string(),
            description: "Fiddle with devices, mechanisms, pick locks".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 4,
        },
        // Prowess actions
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Finesse".to_string(),
            description: "Delicate manipulation, subtle misdirection".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 5,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Prowl".to_string(),
            description: "Move stealthily, infiltrate, climb".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 6,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Skirmish".to_string(),
            description: "Close-quarters combat, melee fighting".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Wreck".to_string(),
            description: "Smash, breach, destroy with brute force".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 8,
        },
        // Resolve actions
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Attune".to_string(),
            description: "Connect with supernatural, channel spirits".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 9,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Command".to_string(),
            description: "Order, compel obedience, intimidate".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Consort".to_string(),
            description: "Socialize, gain access through connections".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Sway".to_string(),
            description: "Influence through charm, reason, or deception".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Command".to_string(),
            description: "Order, compel obedience, intimidate".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 10,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Consort".to_string(),
            description: "Socialize, gain access through connections".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 11,
        },
        Skill {
            id: SkillId::new(),
            world_id,
            name: "Sway".to_string(),
            description: "Influence through charm, reason, or deception".to_string(),
            category: SkillCategory::Approach,
            base_attribute: None, // Blades uses custom attributes, not Stat enum
            is_custom: false,
            is_hidden: false,
            order: 12,
        },
    ]
}
